server:
  port: ${port:8003}


spring:
  redis:
    database: 0
    host: localhost
    port: 6379

# 在dev环境下开启mybatis的日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

#设置域名，资源配置
website:
  domain-name: imoocnews.com